"""adding fk game_id to Team

Revision ID: 79ddfa9b7420
Revises: 0098d344eb40
Create Date: 2022-04-28 14:52:17.530428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ddfa9b7420'
down_revision = '0098d344eb40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'game_id')
    # ### end Alembic commands ###
