"""fixed 1:n relationships

Revision ID: bb622bc61d0c
Revises: 0098d344eb40
Create Date: 2022-04-28 10:19:13.828111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb622bc61d0c'
down_revision = '0098d344eb40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'positions', 'games', ['game_id'], ['id'])
    op.add_column('teams', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'game_id')
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_column('positions', 'game_id')
    # ### end Alembic commands ###
